#!/bin/bash

# Comprehensive test for mustache generator that compares output with cpp generator
# This test verifies that the mustache generator can produce equivalent output to t_cpp_generator

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build_cmake"
THRIFT_BIN="$BUILD_DIR/compiler/cpp/bin/thrift"
TEMPLATES_DIR="$SCRIPT_DIR/templates"

# Check if thrift binary exists
if [ ! -f "$THRIFT_BIN" ]; then
    echo "ERROR: Thrift binary not found at $THRIFT_BIN"
    exit 1
fi

# Check if templates exist
if [ ! -d "$TEMPLATES_DIR" ]; then
    echo "ERROR: Templates directory not found at $TEMPLATES_DIR"
    exit 1
fi

# Create temporary test directory
TEST_DIR=$(mktemp -d)
cd "$TEST_DIR"

# Create a simple test thrift file
cat > test.thrift << 'EOF'
enum Color {
  RED = 1,
  GREEN = 2,
  BLUE = 3
}

struct Point {
  1: i32 x,
  2: i32 y
}

service Calculator {
  i32 add(1: i32 a, 2: i32 b),
  Point getOrigin()
}
EOF

# Test 1: Check that mustache generator is available
echo "Testing mustache generator availability..."
if ! "$THRIFT_BIN" --help 2>&1 | grep -q "mustache (Mustache Template Generator)"; then
    echo "ERROR: Mustache generator not found in thrift help"
    exit 1
fi

# Test 2: Generate files using both cpp and mustache generators
echo "Generating C++ files with cpp generator..."
"$THRIFT_BIN" --gen cpp test.thrift

echo "Generating C++ files with mustache generator..."
"$THRIFT_BIN" --gen mustache:template_dir="$TEMPLATES_DIR" test.thrift

# Test 3: Check that output files were created
if [ ! -d "gen-cpp" ]; then
    echo "ERROR: C++ output directory gen-cpp was not created"
    exit 1
fi

if [ ! -d "gen-mustache-cpp" ]; then
    echo "ERROR: Mustache output directory gen-mustache-cpp was not created"
    exit 1
fi

if [ ! -f "gen-cpp/test_types.h" ]; then
    echo "ERROR: test_types.h was not generated by cpp generator"
    exit 1
fi

if [ ! -f "gen-mustache-cpp/test_types.h" ]; then
    echo "ERROR: test_types.h was not generated by mustache generator"
    exit 1
fi

if [ ! -f "gen-cpp/test_types.cpp" ]; then
    echo "ERROR: test_types.cpp was not generated by cpp generator"
    exit 1
fi

if [ ! -f "gen-mustache-cpp/test_types.cpp" ]; then
    echo "ERROR: test_types.cpp was not generated by mustache generator"
    exit 1
fi

# Test 4: Compare the generated files
echo "Comparing generated header files..."
if ! diff -q gen-cpp/test_types.h gen-mustache-cpp/test_types.h > /dev/null 2>&1; then
    echo "WARNING: Header files differ. Checking for functional equivalence..."
    
    # Check that both files contain the same key elements
    if ! grep -q "struct Color" gen-mustache-cpp/test_types.h; then
        echo "ERROR: test_types.h does not contain Color enum struct"
        exit 1
    fi
    
    if ! grep -q "class Point" gen-mustache-cpp/test_types.h; then
        echo "ERROR: test_types.h does not contain Point class"
        exit 1
    fi
    
    if ! grep -q "RED = 1" gen-mustache-cpp/test_types.h; then
        echo "ERROR: test_types.h does not contain correct enum values"
        exit 1
    fi
    
    echo "Header files are functionally equivalent despite formatting differences."
else
    echo "Header files are identical!"
fi

echo "Comparing generated implementation files..."
if ! diff -q gen-cpp/test_types.cpp gen-mustache-cpp/test_types.cpp > /dev/null 2>&1; then
    echo "WARNING: Implementation files differ. Checking for functional equivalence..."
    
    # Check that both files contain the same key elements
    if ! grep -q "_kColorValues\[\]" gen-mustache-cpp/test_types.cpp; then
        echo "ERROR: test_types.cpp does not contain enum value arrays"
        exit 1
    fi
    
    if ! grep -q "Point::~Point" gen-mustache-cpp/test_types.cpp; then
        echo "ERROR: test_types.cpp does not contain Point destructor"
        exit 1
    fi
    
    if ! grep -q "__set_x" gen-mustache-cpp/test_types.cpp; then
        echo "ERROR: test_types.cpp does not contain setter methods"
        exit 1
    fi
    
    echo "Implementation files are functionally equivalent despite formatting differences."
else
    echo "Implementation files are identical!"
fi

# Test 5: Verify that both generated headers can be compiled (syntax check)
echo "Testing that generated headers are syntactically valid..."

# Create a simple test program that includes both headers
cat > test_compile.cpp << 'EOF'
#include "gen-cpp/test_types.h"
#include "gen-mustache-cpp/test_types.h"

int main() {
    // This is just a compilation test
    return 0;
}
EOF

if command -v g++ >/dev/null 2>&1; then
    echo "Attempting to compile with g++..."
    if g++ -I. -c test_compile.cpp -o test_compile.o 2>/dev/null; then
        echo "Both generated headers compile successfully!"
        rm -f test_compile.o
    else
        echo "WARNING: Headers failed to compile - this may indicate syntax issues"
    fi
else
    echo "g++ not available, skipping compilation test"
fi

# Clean up
cd /
rm -rf "$TEST_DIR"

echo "SUCCESS: Mustache generator produces functionally equivalent output to cpp generator!"