# CMake generated Testfile for 
# Source directory: /home/runner/work/thrift/thrift/lib/cpp/test
# Build directory: /home/runner/work/thrift/thrift/build_full/lib/cpp/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Benchmark "/home/runner/work/thrift/thrift/build_full/bin/Benchmark")
set_tests_properties(Benchmark PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;78;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(UnitTests "/home/runner/work/thrift/thrift/build_full/bin/UnitTests")
set_tests_properties(UnitTests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;99;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(UnitTestsUuid "/home/runner/work/thrift/thrift/build_full/bin/UnitTestsUuid")
set_tests_properties(UnitTestsUuid PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;114;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(UnitTestsUuidNoDirective "/home/runner/work/thrift/thrift/build_full/bin/UnitTestsUuidNoDirective")
set_tests_properties(UnitTestsUuidNoDirective PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;124;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TInterruptTest "/home/runner/work/thrift/thrift/build_full/bin/TInterruptTest" "--" "/home/runner/work/thrift/thrift/lib/cpp/test/../../../test/keys")
set_tests_properties(TInterruptTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;144;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TServerIntegrationTest "/home/runner/work/thrift/thrift/build_full/bin/TServerIntegrationTest")
set_tests_properties(TServerIntegrationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;155;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TransportTest "/home/runner/work/thrift/thrift/build_full/bin/TransportTest")
set_tests_properties(TransportTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;167;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(ZlibTest "/home/runner/work/thrift/thrift/build_full/bin/ZlibTest")
set_tests_properties(ZlibTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;177;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(AnnotationTest "/home/runner/work/thrift/thrift/build_full/bin/AnnotationTest")
set_tests_properties(AnnotationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;186;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(EnumTest "/home/runner/work/thrift/thrift/build_full/bin/EnumTest")
set_tests_properties(EnumTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;194;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TFileTransportTest "/home/runner/work/thrift/thrift/build_full/bin/TFileTransportTest")
set_tests_properties(TFileTransportTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;203;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TFDTransportTest "/home/runner/work/thrift/thrift/build_full/bin/TFDTransportTest")
set_tests_properties(TFDTransportTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;211;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TPipedTransportTest "/home/runner/work/thrift/thrift/build_full/bin/TPipedTransportTest")
set_tests_properties(TPipedTransportTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;218;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(AllProtocolsTest "/home/runner/work/thrift/thrift/build_full/bin/AllProtocolsTest")
set_tests_properties(AllProtocolsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;232;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(DebugProtoTest "/home/runner/work/thrift/thrift/build_full/bin/DebugProtoTest")
set_tests_properties(DebugProtoTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;242;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(JSONProtoTest "/home/runner/work/thrift/thrift/build_full/bin/JSONProtoTest")
set_tests_properties(JSONProtoTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;251;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(OptionalRequiredTest "/home/runner/work/thrift/thrift/build_full/bin/OptionalRequiredTest")
set_tests_properties(OptionalRequiredTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;259;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(RecursiveTest "/home/runner/work/thrift/thrift/build_full/bin/RecursiveTest")
set_tests_properties(RecursiveTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;267;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(SpecializationTest "/home/runner/work/thrift/thrift/build_full/bin/SpecializationTest")
set_tests_properties(SpecializationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;275;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(concurrency_test "/home/runner/work/thrift/thrift/build_full/bin/concurrency_test")
set_tests_properties(concurrency_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;285;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(link_test "/home/runner/work/thrift/thrift/build_full/bin/link_test")
set_tests_properties(link_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;298;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(processor_test "/home/runner/work/thrift/thrift/build_full/bin/processor_test")
set_tests_properties(processor_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;315;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TNonblockingServerTest "/home/runner/work/thrift/thrift/build_full/bin/TNonblockingServerTest")
set_tests_properties(TNonblockingServerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;325;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(TNonblockingSSLServerTest "/home/runner/work/thrift/thrift/build_full/bin/TNonblockingSSLServerTest" "--" "/home/runner/work/thrift/thrift/lib/cpp/test/../../../test/keys")
set_tests_properties(TNonblockingSSLServerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;336;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(OpenSSLManualInitTest "/home/runner/work/thrift/thrift/build_full/bin/OpenSSLManualInitTest")
set_tests_properties(OpenSSLManualInitTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;347;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(SecurityTest "/home/runner/work/thrift/thrift/build_full/bin/SecurityTest" "--" "/home/runner/work/thrift/thrift/lib/cpp/test/../../../test/keys")
set_tests_properties(SecurityTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;358;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
add_test(SecurityFromBufferTest "/home/runner/work/thrift/thrift/build_full/bin/SecurityFromBufferTest" "--" "/home/runner/work/thrift/thrift/lib/cpp/test/../../../test/keys")
set_tests_properties(SecurityFromBufferTest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;369;add_test;/home/runner/work/thrift/thrift/lib/cpp/test/CMakeLists.txt;0;")
